### ISSUE TITLE
simulated metagenomic fasta files

### ISSUE THREAD

**Issue by zachflam** [Strong-Lab/Viral_Classification_in_Metagenomics#1]
Hello,

Can you direct me to the fasta files that were used as input to the various tools for the comparison analysis?

**Comment by glickmac** [comment]
[Supplmental Files](https://github.com/Strong-Lab/Viral_Classification_in_Metagenomics/tree/main/data/Supplemental_Files) contains the genomes used in the simulation. I will have to look into the seed used in InSilcoSeq and post it here. Thanks @zachflam!

**Comment by zachflam** [comment]
Thank you!

**Comment by glickmac** [comment]
InSilicoSeq with a seed of **1** was used on the genomes in listed in the this [supplemental file](https://github.com/Strong-Lab/Viral_Classification_in_Metagenomics/blob/main/data/Supplemental_Files/Supplementary_File_1_Genomes_Used_in_Simulations_By_Complexity.xlsx). Prophage were detected and removed from the genomes prior to simulate assembly.
