### ISSUE TITLE
Binned and assembled reads

### ISSUE THREAD

**Issue by zachflam** [Strong-Lab/Viral_Classification_in_Metagenomics#2]
Are the assembled contigs from the simulated metagenomes available? The contigs that were used as input to the various viral classification tools?

**Comment by zachflam** [comment]
Sorry let me explain this a little better:
I am able to download the fasta files from: https://tinyurl.com/fastavm
Based on the directories in this repo I am unsure if these were the final input sequences to the viral prediction tools or if they need to be cleaned and assembled as described in the methods: 

_After simulating, the reads were perfectly binned by sequence origin to limit the creation of chimeric contigs. Chimeric contigs are assembly errors when reads from different organisms are assembled together resulting in a shorter fragmented assembly or taxonomic misclassification downstream. The decision to bin prior to assembly was to allow for genera labeled contigs in order to explore false positive and recall rates of bacteria and phage, respectively. The perfect bins were assembled using metaSpades (version 3.11.1) and only contigs of length 1KB or greater were retained..._ 

If it is the case that the available fastas require further processing, could you share the assembled contigs?

**Comment by glickmac** [comment]
Hi @zachflam, I forgot about the tinyurl! These the final input contig files into the various viral prediction tools. They are already assembled and ready to go for the tools. I measured performance of the tools by the ability to properly detect the true label (in header of sequences)

**Comment by zachflam** [comment]
Wonderful! Thank you for your responses.
