### ISSUE TITLE
results table used for Figure 3 in final published manuscript

### ISSUE THREAD

**Issue by zachflam** [Strong-Lab/Viral_Classification_in_Metagenomics#3]
Hi! 

Do you have the .csv for the plotted results in the published version of the figure? I think Illumina_Simulations.csv in this repo may be for an older version of that figure concept. 

Thanks for being so responsive! I am working on a project to identify viral contigs in disparate datasets and your work has been tremendous.

**Comment by glickmac** [comment]
Hi @zachflam, I am updating the file now. That sounds exciting about your work!

**Comment by glickmac** [comment]
The files are up in tool performance. I also included the Jupyter Notebook to create the figures in the same[ directory](https://github.com/Strong-Lab/Viral_Classification_in_Metagenomics/tree/main/data/Tool_Performance). Figure_3_4.ipynb is that script.

**Comment by zachflam** [comment]
Awesome! Much thanks!!
